#!/bin/bash

export PYTHONPATH=`pwd`:`pwd`/app

find . -type f \( -name '*.py' -o -name 'Dockerfile'  \) -not -path "*/app/planqtn_cli/dist/*"   -not -path "*/app/ui/public/docs/*" -not -path "*/node_modules/*" | entr -r $@